[features]
seeds = false
skip-lint = false

[programs.localnet]
shadow_delegated_vault = "HGFPeTaz4C3EVz3k4UBAB11g73FxaTAmaKxEQg4SAXpA"

[programs.devnet]
shadow_delegated_vault = "HGFPeTaz4C3EVz3k4UBAB11g73FxaTAmaKxEQg4SAXpA"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/policy-model.mjs"
