[features]
seeds = false
skip-lint = false

[programs.localnet]
shadow_delegated_vault = "H2LRaXnCHp5qc2MECPFLuAVWcFwYqQTi1TgJZJT3tDQc"

[programs.devnet]
shadow_delegated_vault = "H2LRaXnCHp5qc2MECPFLuAVWcFwYqQTi1TgJZJT3tDQc"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node tests/policy-model.mjs"
